- name: Disable local account
  hosts: myhosts
  gather_facts: no
  
  tasks:
   - name: Disable account
     ansible.windows.win_user:
       name: "{{ item }}"
       state: present
       account_disabled: true
     loop: "{{ users }}"

  
