---
- name: Listen for SecureOT alerts
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 192.168.1.116
        port: 5000

  rules:
    - name: Disable account
      condition: event.payload.message == "disable"
      action:
        run_job_template:
          name: disableAccount
          organization: Default
          job_args:
            extra_vars:
              file_path: "{{ event.payload.users }}"

    - name: Delete account
      condition: event.payload.message == "remove"
      action:
        run_job_template:
          name: deleteAccount
          organization: Default
          job_args:
            extra_vars:
              file_path: "{{ event.payload.users }}"
